### ISSUE TITLE
Invalid linecoverage.xml file for Kotlin Test method names that use special symbols enclosed in backticks

### ISSUE THREAD

**Issue by Pfoerd** [hcoles/pitest#1062]
Tested with Pitest 1.9.3. Project runs on Kotlin 1.6.10

# Issue
When setting `exportLineCoverage` to `true` Pitest generates an invalid linecoverage.xml file when there are "special symbols" in test method names enclosed in backticks (this is a best practices for writing tests in Kotlin), e.g. ``@Test fun `this won't work in pitest linecoverage file because of the single quote char`() {...}``.

# Known Workaround
Don't use special symbols in test method names enclosed in backticks

# Proposed Solution
Pitest should escape the special symbols `<, >, &, ', "` in the generated xml files

**Comment by hcoles** [comment]
The XML escaping is a bit of a mess, but should now be fixed by #1091 which will be released in pitest 1.9.6 later today.

The linecoverage xml is not well thought out and needs a rewrite. It was originally intended as an internal debugging tool, rather than for end user use.

Do you have internal reports/tooling that rely on the current format?

**Comment by Pfoerd** [comment]
Thx for fixing this issue timely!

> Do you have internal reports/tooling that rely on the current format?
@hcoles no there is no internal tooling relying on the linecoverage format, we only have problems with it using the report aggregator. Therefore it is not a problem for us to change the format.

**Comment by Pfoerd** [comment]
I tested 1.9.6 and unfortunately I still get invalid linecoverage.xml files. The special characters are escaped correctly in most cases but it seems that there are still some problems with lambdas/inlines where the method name is included in the classname. In that case escaping doensn't work yet.

```kotlin
class FooTest {
    @Test
    fun `foo runs correctly with special characters '&`() {
        val foo = mockk<Foo>()

        every { foo.foo() } returns "string1"
    }
}
```

```xml
<block classname='FooTest$foo runs correctly with special characters '&$1' method='invoke(Lio/mockk/MockKMatcherScope;)Ljava/lang/String;' number='1'><tests>
<test name=FooTest.foo runs correctly with special characters &apos;&amp;'/>
</tests>
</block>
<block classname='FooTest$foo runs correctly with special characters '&$1' method='invoke(Lio/mockk/MockKMatcherScope;)Ljava/lang/String;' number='0'><tests>
<test name='FooTest.foo runs correctly with special characters &apos;&amp;'/>
</tests>
</block>
<block classname='FooTest$foo runs correctly with special characters '&$1' method='invoke(Lio/mockk/MockKMatcherScope;)Ljava/lang/String;' number='2'><tests>
<test name='FooTest.foo runs correctly with special characters &apos;&amp;'/>
</tests>
</block>
<block classname='FooTest$foo runs correctly with special characters '&$1' method='&lt;init&gt;(LFoo;)V' number='0'><tests>
<test name='FooTest.foo runs correctly with special characters &apos;&amp;'/>
</tests>
</block>
<block classname='FooTest$foo runs correctly with special characters '&$1' method='&lt;init&gt;(LFoo;)V' number='1'><tests>
<test name=FooTest.foo runs correctly with special characters &apos;&amp;'/>
</tests>
</block>
```

**Comment by hcoles** [comment]
@Pfoerd I'm not entirely suprised, given that that is mostly hand rolled code rather than something using one of the xml libraries.

I'll take a look today and either rip it all out and replace it with something jacksony, or plug the holes in the escaping.

**Comment by hcoles** [comment]
@Pfoerd Decided to quickly plug the leak. Pitest 1.9.7 should be syncing to maven central now.

**Comment by Pfoerd** [comment]
@hcoles successfully tested it with 1.9.7, it produces valid linecoverage.xml files also for tests with lambdas/inlines like above. Thx!

**Comment by hcoles** [comment]
@Pfoerd are you happy to close this?
